package jmri.jmrit.beantable;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import javax.swing.JFrame;
import javax.swing.JTextField;

import jmri.IdTag;
import jmri.util.JUnitUtil;
import jmri.util.junit.annotations.DisabledIfHeadless;

import org.junit.jupiter.api.*;
import org.netbeans.jemmy.operators.*;

/**
 *
 * @author Paul Bender Copyright (C) 2017
 */
public class IdTagTableActionTest extends AbstractTableActionBase<IdTag> {

    @Test
    public void testCTor() {
        assertNotNull( a, "exists");
    }

    @Override
    public String getTableFrameName() {
        return Bundle.getMessage("TitleIdTagTable");
    }

    @Override
    @Test
    public void testGetClassDescription() {
        assertEquals( "ID Tag Table", a.getClassDescription(),
                "IdTag Table Action class description");
    }

    /**
     * Check the return value of includeAddButton. The table generated by this
     * action includes an Add Button.
     */
    @Override
    @Test
    public void testIncludeAddButton() {
        assertTrue( a.includeAddButton(), "Default include add button");
    }

    @Override
    public String getAddFrameName() {
        return Bundle.getMessage("TitleAddIdTag");
    }

    @Test
    @Override
    @DisabledIfHeadless
    public void testAddThroughDialog() {

        assertTrue(a.includeAddButton());
        a.actionPerformed(null);
        JFrame f = JFrameOperator.waitJFrame(getTableFrameName(), true, true);

        // find the "Add... " button and press it.
        jmri.util.swing.JemmyUtil.pressButton(new JFrameOperator(f), Bundle.getMessage("ButtonAdd"));
        new org.netbeans.jemmy.QueueTool().waitEmpty();
        JFrame f1 = JFrameOperator.waitJFrame(getAddFrameName(), true, true);
        JFrameOperator jf = new JFrameOperator(f1);
        //Enter 1 in the text field labeled "System Name:"
        JLabelOperator jlo = new JLabelOperator(jf, Bundle.getMessage("LabelSystemName"));
        (new JTextFieldOperator((JTextField) jlo.getLabelFor())).typeText("1");
        //and press OK 
        jmri.util.swing.JemmyUtil.pressButton(jf, Bundle.getMessage("ButtonOK"));
        JUnitUtil.dispose(f1);
        JUnitUtil.dispose(f);
    }

    @Test
    @Disabled("IdTag table has no Edit button")
    @Override
    public void testEditButton() {
    }

    @BeforeEach
    @Override
    public void setUp() {
        JUnitUtil.setUp();
        JUnitUtil.resetProfileManager();
        JUnitUtil.initIdTagManager();
        helpTarget = "package.jmri.jmrit.beantable.IdTagTable";
        a = new IdTagTableAction();
    }

    @AfterEach
    @Override
    public void tearDown() {
        jmri.InstanceManager.getDefault(jmri.IdTagManager.class).dispose();
        a = null;
        JUnitUtil.tearDown();
    }

    // private final static Logger log = LoggerFactory.getLogger(IdTagTableActionTest.class);
}
