package jmri.jmrit.beantable;


import jmri.util.JUnitUtil;

import org.junit.Assert;
import org.junit.jupiter.api.*;

import jmri.time.TimeProvider;

/**
 * Tests for classes in the jmri.jmrit.beantable package
 *
 * @author Bob Jacobsen      Copyright 2004 (ClockTableActionTest)
 * @author Daniel Bergqvist  Copyright 2025
 */
public class TimeProviderTableActionTest extends AbstractTableActionBase<TimeProvider> {

    @Test
    public void testCreate() {
        Assert.assertNotNull(a);
    }

    @Override
    public String getTableFrameName() {
        return Bundle.getMessage("TitleClockTable");
    }

    @Override
    @Test
    public void testGetClassDescription() {
        Assert.assertEquals("Clock Table Action class description", "Clock Table", a.getClassDescription());
    }

    /**
     * Check the return value of includeAddButton. The table generated by this
     * action includes an Add Button.
     */
    @Override
    @Test
    public void testIncludeAddButton() {
//        Assert.assertTrue("Default include add button", a.includeAddButton());
        Assert.assertFalse("Default include add button", a.includeAddButton());
    }

    @Override
    public String getAddFrameName() {
        return Bundle.getMessage("TitleAddClock");
    }

    @Disabled
    @Test
    @Override
    public void testAddButton() {
    }

    @Test
    @Disabled("no Edit button in clock Table")
    @Override
    public void testEditButton() {
    }

    @BeforeEach
    @Override
    public void setUp() {
        JUnitUtil.setUp();
        jmri.util.JUnitUtil.resetProfileManager();
        jmri.util.JUnitUtil.initDefaultUserMessagePreferences();
        helpTarget = "package.jmri.jmrit.beantable.ClockTable";
        a = new TimeProviderTableAction();
    }

    @AfterEach
    @Override
    public void tearDown() {
        JUnitUtil.tearDown();
        a = null;
    }

}
