package jmri.util;

import java.awt.Component;
import java.util.function.Function;
import java.util.function.Predicate;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 * A helper Panel for input-validating input boxes. It converts & validates the
 * text input, disabling {@link #confirmUI} component (usually a button) when
 * the input is not valid.
 * 
 * @author Svata Dedic Copyright (c) 2019
 */
final class ValidatingInputPane<T> extends javax.swing.JPanel  {
    private final Function<String, T> convertor;
    private final DocumentListener l = new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            validateInput();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            validateInput();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    };

    /**
     * Callback that validates the input after conversion.
     */
    private Predicate<T>    validator;

    /**
     * The confirmation component. The component is disabled when the
     * input is rejected by converter or validator
     */
    private JComponent      confirmUI;
    
    /**
     * Holds the last seen error. {@code null} for no error - valid input
     */
    private String lastError;
    
    /**
     * Creates new form ValidatingInputPane.
     * @param convertor converts String to the desired data type.
     */
    public ValidatingInputPane(Function<String, T> convertor) {
        initComponents();
        errorMessage.setVisible(false);
        this.convertor = convertor;
    }
    
    ValidatingInputPane<T> attachConfirmUI(JComponent confirm) {
        this.confirmUI = confirm;
        return this;
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        inputText.getDocument().addDocumentListener(l);
        SwingUtilities.invokeLater(this::validateInput);
    }
    
    ValidatingInputPane<T> message(String msg) {
        promtptMessage.setText(msg);
        return this;
    }
    
    ValidatingInputPane<T> validator(Predicate<T> val) {
        this.validator = val;
        return this;
    }
    
    boolean hasError() {
        return lastError != null;
    }
    
    void setText(String text) {
        inputText.setText(text);
    }
    
    String getText() {
        return inputText.getText().trim();
    }
    
    T getValue() {
        String s = getText();
        return s.isEmpty() ? null : convertor.apply(s);
    }
    
    private void validateInput() {
        if (isVisible()) {
            validate(getText());
        }
    }
    
    private void clearErrors() {
        if (confirmUI != null) {
            confirmUI.setEnabled(true);
            errorMessage.setText("");
            errorMessage.setVisible(false);
        }
        lastError = null;
    }
    
    private void validate(String text) {
        String msg;
        if (text.isEmpty()) {
            clearErrors();
            return;
        }
        try {
            T value = convertor.apply(text);
            if (validator == null || 
                validator.test(value)) {
                clearErrors();
                return;
            }
            msg = Bundle.getMessage("InputDialogError");
        } catch (IllegalArgumentException ex) {
            msg = ex.getLocalizedMessage();
        }
        lastError = msg;
        errorMessage.setText(msg);
        errorMessage.setVisible(true);
        if (confirmUI != null) {
            confirmUI.setEnabled(false);
        }
        Component c = SwingUtilities.getRoot(this);
        c.invalidate();
        if (c instanceof JDialog) {
            ((JDialog)c).pack();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        promtptMessage = new javax.swing.JLabel();
        inputText = new javax.swing.JTextField();
        errorMessage = new javax.swing.JTextArea();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        promtptMessage.setText(" ");

        errorMessage.setEditable(false);
        errorMessage.setBackground(getBackground());
        errorMessage.setColumns(20);
        errorMessage.setForeground(java.awt.Color.red);
        errorMessage.setRows(2);
        errorMessage.setToolTipText("");
        errorMessage.setAutoscrolls(false);
        errorMessage.setBorder(null);
        errorMessage.setFocusable(false);
        errorMessage.setRequestFocusEnabled(false);
        errorMessage.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promtptMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(inputText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(promtptMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea errorMessage;
    private javax.swing.JTextField inputText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel promtptMessage;
    // End of variables declaration//GEN-END:variables
}
