/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmri.jmrit.ctc.editor.gui;

import jmri.jmrit.ctc.editor.code.AwtWindowProperties;
import jmri.jmrit.ctc.editor.code.Columns;

/**
 *
 * @author Gregory J. Bedlek Copyright (C) 2018, 2019
 */
public class DlgFixErrors extends javax.swing.JDialog {

    private static final String FORM_PROPERTIES = "DlgFixErrors";
    private final AwtWindowProperties _mAwtWindowProperties;
    private final Columns _mColumns;
    
    public DlgFixErrors(java.awt.Frame parent, boolean modal, AwtWindowProperties awtWindowProperties, Columns columns) {
        super(parent, modal);
        initComponents();
        _mAwtWindowProperties = awtWindowProperties;
        _mColumns = columns;
        _mAwtWindowProperties.setWindowState((java.awt.Window)this, FORM_PROPERTIES);
        this.getRootPane().setDefaultButton(_mCancel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _mInfo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        _mCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fix errors:");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        _mInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        _mInfo.setText("<html>NOTE: The purpose of this routine is to go thru every column and automatically de-enable sub-system(s) that are in error. Any data that you have already entered is NOT lost, just \"ignored\".  This routine CANNOT fix missing data in the Code Button sub-system, since there is no way to de-check that.  You have two choices in this situation after this routine runs: Delete those column(s) or edit it and fix them.</html>");
        _mInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        _mInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        _mInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        _mCancel.setText("Cancel");
        _mCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _mCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_mInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(_mCancel)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_mInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(_mCancel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exitDialog();
    }//GEN-LAST:event_formWindowClosing

    private void _mCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__mCancelActionPerformed
        exitDialog();
    }//GEN-LAST:event__mCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        _mColumns.fixAllErrors();
        exitDialog();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitDialog() {
        _mAwtWindowProperties.saveWindowState(this, FORM_PROPERTIES);
        dispose();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _mCancel;
    private javax.swing.JLabel _mInfo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
