
package jmri.jmrix.loconet;

import junit.framework.*;


import apps.tests.*;

/**
 * Generated by JBuilder
 * <p>Title: LnPacketizerTest </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2002</p>
 * @author Bob Jacobsen
 * @version $Id: LnPacketizerTest.java,v 1.1 2002-03-18 02:11:27 jacobsen Exp $
 */
public class LnPacketizerTest extends TestCase {
  Log4JFixture log4jfixtureInst = new Log4JFixture(this);

  public LnPacketizerTest(String s) {
    super(s);
  }

  protected void setUp() {
    log4jfixtureInst.setUp();
  }

  protected void tearDown() {
    log4jfixtureInst.tearDown();
  }

  public void testDummy() {}

}
