/*
 * Template for the web app script generated by JMRI.
 * 
 * This template will be completed with dependences (item 1), routes (2),
 * navigation menu items (3), and additional providers (4)
 */

// create the jmri.app module
angular.module('jmri.app', [
  // dependencies %1$s
]);

// configure the jmri.app module
angular.module('jmri.app').config(['$routeProvider',
  function ($routeProvider) {
    'use strict';

    $routeProvider
    // routes %2$s
    // Default
    .otherwise({redirectTo: '/'});
  }
]);

// add the navigation menu controller to the jmri.app module
angular.module('jmri.app').controller('NavigationCtrl', ['$scope', '$http',
  function ($scope, $http) {
    // navigation items %3$s

    // about display
    $http.get('/app/about').then(function (response) {
      $scope.additionalInfo = response.data.additionalInfo;
      $scope.copyright = response.data.copyright;
      $scope.imgAlt = response.data.imgAlt;
      $scope.imgSrc = response.data.imgSrc;
      $scope.title = response.data.title;
      $scope.productInfo = response.data.productInfo;
    });
    $scope.openAboutModal = function () {
      $scope.isAboutModalOpen = true;
    };
    $scope.onAboutModalClose = function() {
      $scope.isAboutModalOpen = false;
    };
  }
]);

// additional providers %4$s