/*
 * Template for the web app script generated by JMRI.
 * 
 * This template will be completed with dependences (item 1), routes (2),
 * navigation menu items (3), and additional providers (4)
 */

// create the jmri.app module
angular.module('jmri.app', [
  // dependencies %1$s
]);

// configure the jmri.app module
angular.module('jmri.app').config(['$routeProvider',
  function ($routeProvider) {
    'use strict';

    $routeProvider
    // routes %2$s
    // Default
    .otherwise({redirectTo: '/'});
  }
]);

// add the navigation menu controller to the jmri.app module
angular.module('jmri.app').controller('NavigationCtrl', ['$scope', '$http', '$jsonSocket', '$log', '$interval',
  function ($scope, $http, $jsonSocket, $log, $interval) {
    // navigation items %3$s

    // about display
    $http.get('/app/about').then(function (response) {
      $scope.additionalInfo = response.data.additionalInfo;
      $scope.copyright = response.data.copyright;
      $scope.imgAlt = response.data.imgAlt;
      $scope.imgSrc = response.data.imgSrc;
      $scope.title = response.data.title;
      $scope.productInfo = response.data.productInfo;
    });
    $scope.openAboutModal = function () {
      $scope.isAboutModalOpen = true;
    };
    $scope.onAboutModalClose = function() {
      $scope.isAboutModalOpen = false;
    };
    
    // core socket services (power and keep alive)
    $scope.heartbeat;
    $scope.startHeartbeat = function(heartbeat) {
      $log.info("Starting heartbeat every " + heartbeat + " ms.");
      if (angular.isDefined($scope.heartbeat)) {
        return;
      }
      $scope.heartbeat = $interval(function() {
        $jsonSocket.ping();
      }, heartbeat);
    };
    $scope.stopHeartbeat = function() {
      if (angular.isDefined(heartbeat)) {
        $interval.cancel(heartbeat);
        heartbeat = undefined;
      }
    };
    $scope.power = [];
    $jsonSocket.register({
      open: function() {
        // will likely cause power to be listed twice
        socket.list('power');
      },
      power: function(m) {
        $log.info('got power ' + m.data.name + " (" + m.data.state + ")");
        var found = false;
        for (var i in $scope.power) {
            if ($scope.power[i].name === m.data.name) {
                $scope.power[i].state = m.data.state;
                found = true;
            }
        }
        if (!found) {
            $scope.power.push(m.data);
            socket.getPower(m.name);
        }
      },
      hello: function(m) {
        $scope.startHeartbeat(m.data.heartbeat);
      },
      pong: function(m) {
        $log.info("Received pong");
      },
      close: function() {
        $scope.stopHeartbeat();
      }
      
    });
    $jsonSocket.list('power');
    
  }
]);

angular.module('jmri.app').filter('triStateCheckBox', function() {
  return function(input) {
    switch(input) {
      case 4: // off
        return 'fa-square';
        break;
      case 2: // on
        return 'fa-check-square';
        break;
      default: // unknown
        return 'fa-minus-square';
    }
  };
});
// additional providers %4$s