#! /bin/csh

#
# Do an in-place transform on a file
#   ./xml/XSLT/doOneXSLT xml/XSLT/a.xsl  xml/decoders/b.xml
#
# Known to work on Mac OS X, expected to work on Linux, Windows situation not clear.
#
#  Bob Jacobsen 11/2015
# 

mkdir tmp >& /dev/null

rm -f tmp/testDecoder.xml

xsltproc $1 $2 > tmp/testDecoder.xml

mv tmp/testDecoder.xml $2

