#! /bin/csh

#
# Put JMRI decoder file(s) in normal form.
#
#*) If there's no item attribute, create from the label attribute
#*) Create a label element with default language if none present.
#*) Removing redundant label attributes from variable elements:   
#*) Standardize layout of the content
#
# Output is sent to a (created, if need be) tmp subdirectory in the wd, using the
# same file names.
#
# Known to work on Mac OS X, expected to work on Linux, Windows situation not clear.
#
#  Bob Jacobsen 3/2014
# 
mkdir tmp >& /dev/null
foreach x ( $* )
 cat $x |\
    xsltproc decoderLabelToItem.xsl - |\
    xsltproc decoderAddLabelElement.xsl - |\
    xsltproc decoderPaneLabelToText.xsl - |\
    xsltproc decoderAddPaneLabelTextElement.xsl - |\
    xsltproc decoderAddI18nLabel.xsl - |\
    xsltproc decoderAddI18nComment.xsl - |\
    xsltproc decoderAddI18nChoice.xsl - |\
    xsltproc decoderAddI18nName.xsl - |\
    xsltproc decoderAddI18nTooltip.xsl - |\
    xsltproc decoderAddI18nPaneTooltip.xsl - |\
    xsltproc decoderAddI18nPaneLabel.xsl - |\
    xsltproc decoderSuppressRedundantLabel.xsl - |\
    xsltproc decoderPaneSuppressLabelAttribute.xsl - |\
    xmllint -format - > tmp/$x:t
# cat $x | xmllint -format - > tmp/$x:t
end

# full string, including translation
#  cat $x | xsltproc decoderLabelToItem.xsl - | xsltproc decoderAddLabelElement.xsl - | xsltproc decoderAddI18nLabel.xsl - | xsltproc decoderAddI18nComment.xsl - | xsltproc decoderAddI18nChoice.xsl - | xsltproc decoderAddI18nName.xsl - | xsltproc decoderAddI18nTooltip.xsl - | xsltproc decoderAddI18nPaneTooltip.xsl - | xsltproc decoderAddI18nPaneLabel.xsl - | xsltproc decoderSuppressRedundantLabel.xsl - | tr -d '\r' | xmllint -format - > tmp/$x:t

# full string, no translation
# cat $x | xsltproc decoderLabelToItem.xsl - | xsltproc decoderAddLabelElement.xsl - | xsltproc decoderSuppressRedundantLabel.xsl - | xsltproc decoderAddI18nLabel.xsl - | xsltproc decoderAddI18nComment.xsl - | xsltproc decoderAddI18nChoice.xsl - | xsltproc decoderAddI18nName.xsl - | xsltproc decoderAddI18nTooltip.xsl - | xsltproc decoderAddI18nPaneTooltip.xsl - | tr -d '\r' | xmllint -format - > tmp/$x:t

# just formatting
# cat $x | tr -d '\r' | xmllint -format - > tmp/$x:t

