#! /bin/csh

#
# Put JMRI decoder file(s) in normal form.
#
#*) If there's no item attribute, create from the label attribute
#*) Create a label element with default language if none present.
#*) Removing redundant label attributes from variable elements:   
#*) Standardize layout of the content
#
# Output is sent to a (created, if need be) tmp subdirectory in the wd, using the
# same file names.
#
# Known to work on Mac OS X, expected to work on Linux, Windows situation not clear.
#
#  Bob Jacobsen 3/2014
# 
mkdir tmp >& /dev/null
foreach x ( $* )
 cat $x |\
    xsltproc decoderLabelToItem.xsl - |\
    xsltproc decoderAddLabelElement.xsl - |\
    xsltproc decoderPaneAddNameElement.xsl - |\
    xsltproc decoderPaneLabelToText.xsl - |\
    xsltproc decoderAddPaneLabelTextElement.xsl - |\
    xsltproc decoderSuppressRedundantLabel.xsl - |\
    xsltproc decoderPaneSuppressLabelAttribute.xsl - |\
    xsltproc decoderPaneSuppressNameAttribute.xsl - |\
    xmllint -format - > tmp/$x:t
end


# just formatting
# cat $x | tr -d '\r' | xmllint -format - > tmp/$x:t

# with translation
#  cat $x |\
#     xsltproc decoderLabelToItem.xsl - |\
#     xsltproc decoderAddLabelElement.xsl - |\
#     xsltproc decoderPaneAddNameElement.xsl - |\
#     xsltproc decoderPaneLabelToText.xsl - |\
#     xsltproc decoderAddPaneLabelTextElement.xsl - |\
#     xsltproc decoderSuppressRedundantLabel.xsl - |\
#     xsltproc decoderPaneSuppressLabelAttribute.xsl - |\
#     xsltproc decoderPaneSuppressNameAttribute.xsl - |\
#     xsltproc decoderAddI18nLabel.xsl - |\
#     xsltproc decoderAddI18nComment.xsl - |\
#     xsltproc decoderAddI18nChoice.xsl - |\
#     xsltproc decoderAddI18nTooltip.xsl - |\
#     xsltproc decoderPaneAddI18nName.xsl - |\
#     xsltproc decoderAddI18nPaneLabel.xsl - |\
#     xsltproc decoderAddI18nPaneTooltip.xsl - |\
#     xmllint -format - > tmp/$x:t
