#! /bin/bash
# 
# Run all the XML schema, load-and-store and similar tests
#
# Argument, if present, is a starting _directory_ under java/test, e.g. "jmri/managers"
#  
# The list of test files that fail goes into /failed_files.txt
#
# Assumes that a build step i.e. "ant tests" has already taken place, so that 
# individual test classes are ready to run. 
#

rm -f ./failed_files.txt
touch ./failed_files.txt

unset JMRI_OPTIONS

./runtest.csh jmri/configurexml/LoadAndCheckTest || echo ${jmri_test} >> ./failed_files.txt

for jmri_test in $( find java/test/$1 -name LoadAndStoreTest.java -print) 
    do jmri_test=${jmri_test#java/test/} 
        jmri_test=${jmri_test%\.java}
        # date
        echo ${jmri_test}
        ./runtest.csh ${jmri_test} || echo ${jmri_test} >> ./failed_files.txt
done

for jmri_test in $( find java/test/$1 -name SchemaTest.java -print) 
    do jmri_test=${jmri_test#java/test/} 
        jmri_test=${jmri_test%\.java}
        # date
        echo ${jmri_test}
        ./runtest.csh ${jmri_test} || echo ${jmri_test} >> ./failed_files.txt
done

./runtest.csh jmri/implementation/SignalSystemFileCheckTest || echo ${jmri_test} >> ./failed_files.txt

./runtest.csh jmri/jmrit/symbolicprog/tabbedframe/CheckProgrammerNamesTest|| echo ${jmri_test} >> ./failed_files.txt

# error exit if any failed
if [ -s ./failed_files.txt ]; then echo "The following files failed"; cat ./failed_files.txt; exit 1; fi
