#! /bin/csh

#
# Check the operation of putting decoders in normal form
#
# Uses the tmp directory
#
# Known to work on Mac OS X, expected to work on Linux, Windows situation not clear.
#
#  Bob Jacobsen 3/2014
# 
mkdir tmp >& /dev/null

rm -f tmp/testDecoder.xml

./normalizeDecoder testDecoder.xml

diff testDecoder.xml.result tmp/testDecoder.xml

./normalizeDecoder testPane.xml

diff testPane.xml.result tmp/testPane.xml

