package jmri.util;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.junit.Assert;
import org.junit.jupiter.api.*;

/**
 * Builds the help index page for the JMRI help pages that's accessed as files
 * by the user's web browser.
 * 
 * @author Daniel Bergqvist  Copyright (C) 2021
 */
public class BuildHelpStubFilesTest {

    private final String template;
    
    
    private PrintWriter mapJhmWriter;
    
    // The main() method is used when this class is run directly from ant
    static public void main(String[] args) throws IOException, JDOMException {
        new BuildHelpStubFilesTest().build();
        System.exit(0);
    }
    
    
    public BuildHelpStubFilesTest() throws IOException {
        Path path = Path.of(FileUtil.getProgramPath() + "help/en/local/stub_template.html");
        template = Files.readString(path);
    }
    
    private class XmlFile extends jmri.jmrit.XmlFile {
    }
    
    private void generateStubFile(String helpKey) throws IOException {
        Path path = Path.of(FileUtil.getProgramPath() + "help/en/local/stub/"+helpKey+".html");
        if (Files.exists(path)) {
            System.out.format("The file for tag %s already exists%n", helpKey);
        }
        FileWriter fileWriter = new FileWriter(FileUtil.getProgramPath() + "help/en/local/stub/"+helpKey+".html");
        try (PrintWriter printWriter = new PrintWriter(fileWriter)) {
            String contents = template.replaceFirst("<!--HELP_KEY-->", helpKey);
            printWriter.print(contents);
        }
    }
    
    private void parseElement(Element e, boolean generateStubFiles) throws IOException {
        String helpKey = e.getAttributeValue("target");
        if ("tocitem".equals(e.getName())) {
            if (generateStubFiles && (helpKey != null)) {
                generateStubFile(helpKey);
            }
        }
        if (helpKey != null) {
            String expandedHelpKey = helpKey.replace(".", "/");
            int pos = expandedHelpKey.lastIndexOf('_');
            if (pos == -1) {
                expandedHelpKey = expandedHelpKey + ".shtml";
            } else {
                expandedHelpKey = expandedHelpKey.substring(0, pos) + ".shtml"
                        + "#" + expandedHelpKey.substring(pos+1);
            }
            mapJhmWriter.format("<mapID target=\"%s\" url=\"%s\"/>%n", helpKey, expandedHelpKey);
        }
        for (Element child : e.getChildren()) {
            parseElement(child, generateStubFiles);
        }
    }
    
    private void buildIndex() throws JDOMException, IOException {
        FileWriter fileWriter = new FileWriter(FileUtil.getProgramPath() + "help/en/local/Map.jhm");
        mapJhmWriter = new PrintWriter(fileWriter);
        
        mapJhmWriter.println("<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>");
        mapJhmWriter.println("<!DOCTYPE index PUBLIC \"Help Index\" \"http://java.sun.com/products/javahelp/index_2_0.dtd\"><!--generated by jmri.util.BuildHelpStubFilesTest -->");
        mapJhmWriter.println("<map version=\"1.0\">");
        
        XmlFile xmlFile = new XmlFile();
        Assert.assertNotNull(xmlFile);
        Element e = xmlFile.rootFromName(FileUtil.getProgramPath() + "help/en/JmriHelp_enTOC.xml");
        Assert.assertNotNull(e);
        parseElement(e, true);
        
        xmlFile = new XmlFile();
        Assert.assertNotNull(xmlFile);
        e = xmlFile.rootFromName(FileUtil.getProgramPath() + "help/en/JmriHelp_enIndex.xml");
        Assert.assertNotNull(e);
        parseElement(e, false);
        
        mapJhmWriter.println("</map>");
        mapJhmWriter.close();
    }

    private void build() throws JDOMException, IOException {
        buildIndex();
    }


    @Test
    public void testBuildIndex() throws JDOMException, IOException {
        build();
    }

    @BeforeEach
    public void setUp() {
        JUnitUtil.setUp();

    }

    @AfterEach
    public void tearDown() {
        JUnitUtil.tearDown();
    }
}
